name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Publish framework dependent
      run: |
        pwd
        dotnet publish -c Release --self-contained false -p:PublishSingleFile=true -r win-x64
        find ./ -type d
    - name: Upload framework-dependent-win-x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: framework-dependent-win-x64
        path: csharp/bin/Release/netcoreapp3.1/win-x64/publish

