name: Publish

on:
  push:
      tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Publish framework dependent
      run: |
        dotnet publish -c Release --self-contained false -p:PublishSingleFile=true -r win-x64 -o publish-framework-dependent-win-x64
        dotnet publish -c Release --self-contained true -p:PublishSingleFile=true -r win-x64 -o publish-self-contained-win-x64
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "publish-framework-dependent-win-x64/*,publish-self-contained-win-x64/*"
        token: ${{ secrets.GITHUB_TOKEN }}
